### ISSUE TITLE
[@nativescript/geolocation] -  Cannot read property 'common' of undefined

### ISSUE THREAD

**Issue by elynyomas** [NativeScript/plugins#160]
I can't use this plugin after upgrading my project to version 8.

Using `Geolocation.enableLocationRequest()` throws this error:

```
JS: ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'common' of undefined
JS: TypeError: Cannot read property 'common' of undefined
JS:     at _isGooglePlayServicesAvailable (file: src/webpack:/app/node_modules/@nativescript/geolocation/index.android.js:250:0)
JS:     at file: src/webpack:/app/node_modules/@nativescript/geolocation/index.android.js:234:0
JS:     at new ZoneAwarePromise (file: src/webpack:/app/node_modules/zone.js/fesm2015/zone.js:1387:0)
JS:     at _makeGooglePlayServicesAvailable (file: src/webpack:/app/node_modules/@nativescript/geolocation/index.android.js:233:0)
JS:     at file: src/webpack:/app/node_modules/@nativescript/geolocation/index.android.js:202:0
JS:     at ZoneDelegate.invoke (file: src/webpack:/app/node_modules/zone.js/fesm2015/zone.js:372:0)
JS:     at Object.onInvoke (file: src/webpack:/app/node_modules/@angular/core/fesm2015/core.js:28672:0)
JS:     at ZoneDelegate.invoke (file: src/webpack:/app/node_modules/zone.js/fesm2015/zone.js:371:0)
JS:     at Zone.run (file: src/webpack:/app/node_modules/zone.js/fesm2015/zone.js:134:0)
JS:     at file:///data/data/org.nat...

```

I've tried to add this to the `before-plugins.gradle`, the same error came up

```
android {  
  // other stuff here

  project.ext {
    googlePlayServicesVersion = "16.+"
  }
}
```

Permissions are set too. What am I missing?

**Comment by elynyomas** [comment]
UPDATE: 
It came up it was an issue with the way I added to an xplat workspace.
Following this fixed the issues:
https://github.com/nstudio/xplat/issues/197
