### ISSUE TITLE
[@nativescript/geolocation] - Error: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference

### ISSUE THREAD

**Issue by jeanpaulattard** [NativeScript/plugins#165]
The following exception is being thrown whenever I call the `enableLocationRequest()` method.

```
 Error: Uncaught (in promise): Error: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
JS: _systemDialogWillShow(file:///data/user/0/<directory>/files/app/vendor.js:145569:61)
JS:     at (file:///data/user/0/<directory>/files/app/vendor.js:145468:14)
JS:     at ZoneAwarePromise(file:///data/user/0/<directory>/files/app/vendor.js:146586:29)
JS:     at enableLocationRequest(file:///data/user/0/<directory>/files/app/vendor.js:145465:12)
JS:     at (file:///data/user/0/<directory>/files/app/bundle.js:441:79)
JS:     at ZoneDelegate.invoke(file:///data/user/0/<directory>/files/app/vendor.js:146072:26)
JS:     at onInvoke(file:///data/user/0/<directory>/files/app/vendor.js:73479:33)
JS:     at ZoneDelegate.invoke(file:///data/user/0/<directory>/files/app/vendor.js:146071:32)
JS:     at...

```

In the ngOnInit of my component, I'm calling the following piece of code

```
import { enableLocationRequest, isEnabled } from '@nativescript/geolocation';

...

isEnabled().then((enabled: boolean) => {
    if (!enabled) {
        return enableLocationRequest(true, true);
    }
});
```

This is happening on Android 11. Below are my gradle files and the permissions I have in the AndroidManifest.xml

```
android {
  defaultConfig {
    minSdkVersion 22
    generatedDensities = []
  }
  aaptOptions {
    additionalParameters "--no-version-vectors"
  }
}
```

```
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
```

Am I missing something? This is happening every time that method is called, and according to the docs that's all that is required to request location. Thanks in advance.

Package.json include the following versions

```
"@angular/animations": "~11.2.7",
    "@angular/cdk": "10.2.5",
    "@angular/common": "~11.2.7",
    "@angular/compiler": "~11.2.7",
    "@angular/core": "~11.2.7",
    "@angular/forms": "~11.2.7",
    "@angular/material": "10.2.5",
    "@angular/platform-browser": "~11.2.7",
    "@angular/platform-browser-dynamic": "~11.2.7",
    "@angular/router": "~11.2.7",
    "@nativescript/angular": "~11.8.0",
    "@nativescript/core": "~8.0.0",
    "@nativescript/geolocation": "7.2.1",
    "@nativescript/theme": "3.0.0",
    "nativescript-permissions": "1.3.11",
    "reflect-metadata": "0.1.13",
    "rxjs": "~6.6.7",
    "tslib": "2.0.3",
    "zone.js": "~0.11.1"
```

**Comment by yencolon** [comment]
Any soution? I ran into the same issue

**Comment by Cersin** [comment]
+ anybody?

**Comment by yencolon** [comment]
@Cersin be sure the permissions are in the manifest file and check this [known issue ](https://www.npmjs.com/package/@nativescript/geolocation) (check the bottom of the page). That helped me.

**Comment by Cersin** [comment]
@yencolon still not working, i got all permission in manifest.
Same on ionic with geolocation works...

**Comment by Cersin** [comment]
@yencolon i have this error:
JS: Error: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.app.Activity.shouldShowRequestPermissionRationale(java.lang.String)' on a null object reference

**Comment by canmertc** [comment]
@jeanpaulattard, @Cersin
The plugin versions 7.2.1 and 7.2.2 were thrown the same error on Android. Downgrading to the previous version that I was using (7.0.0 in my case) has worked for now. I haven't tried the versions between them

**Comment by canmertc** [comment]
Upgraded the plugin to v8.0.1. But still throws the same error
```
JS: Error: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.app.Activity.shouldShowRequestPermissionRationale(java.lang.String)' on a null object reference
```
**Workaround:**
Checking if there is a foreground activity on Android, before requesting the location has cleared the error.
```
if (isAndroid && !Application.android.foregroundActivity) {
    return
}
geolocation.enableLocationRequest();
```
