### ISSUE TITLE
[fingerprint-auth] Using pin fallback throws an error

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/plugins#202]
This is tested on Android 30 emulator. On the finger prompt, press use pin and enter a correct pin. 

```
System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method onAuthenticationSucceeded failed
System.err: Error: javax.crypto.IllegalBlockSizeException
System.err: 
System.err: StackTrace:
System.err: onAuthenticationSucceeded(file: node_modules/@nativescript/fingerprint-auth/index.android.js:21:0)
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1302)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1188)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1175)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1153)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1149)
System.err:     at com.tns.gen.androidx.biometric.BiometricPrompt_AuthenticationCallback_vendor_46469_90_.onAuthenticationSucceeded(BiometricPrompt_AuthenticationCallback_vendor_46469_90_.java:27)
System.err:     at androidx.biometric.BiometricFragment$9.run(BiometricFragment.java:907)
System.err:     at android.os.Handler.handleCallback(Handler.java:938)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
System.err:     at android.os.Looper.loop(Looper.java:223)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:7656)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
System.err: Caused by: javax.crypto.IllegalBlockSizeException
System.err:     at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:519)
System.err:     at javax.crypto.Cipher.doFinal(Cipher.java:2055)
System.err:     ... 15 more
System.err: Caused by: android.security.KeyStoreException: Key user not authenticated
System.err:     at android.security.KeyStore.getKeyStoreException(KeyStore.java:1301)
System.err:     at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.update(KeyStoreCryptoOperationChunkedStreamer.java:140)
System.err:     at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:169)
System.err:     at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)
System.err:     ... 16 more
```

**Comment by jcassidyav** [comment]
Supported via the [Biometrics](https://github.com/NativeScript/plugins/tree/main/packages/biometrics) plugin,
@nativescript/fingerprint-auth is depreciated.
