### ISSUE TITLE
[@nativescript/google-signin] Failed resolution of: Lkotlin/jvm/internal/Intrinsics when invoking GoogleSignin.configure

### ISSUE THREAD

**Issue by rbudnar** [NativeScript/plugins#205]
Hi! I'm testing out the google-signin plugin on a blank NS 8 project (android) and when I call `GoogleSignin.configure({...})`, I receive the following error: `ERROR Error: Uncaught (in promise): Error: java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;`

Full stack trace:
<details>

```
ERROR Error: Uncaught (in promise): Error: java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
(file:///data/data/org.nativescript.testkt/files/app/vendor.js:114855:64)
	at ZoneAwarePromise(file:///data/data/org.nativescript.testkt/files/app/vendor.js:144232:29)
	at configure(file:///data/data/org.nativescript.testkt/files/app/vendor.js:114854:16)
	at ngOnInit(file:///data/data/org.nativescript.testkt/files/app/bundle.js:267:79)
	at callHook(file:///data/data/org.nativescript.testkt/files/app/vendor.js:16952:22)
	at callHooks(file:///data/data/org.nativescript.testkt/files/app/vendor.js:16921:17)
	at executeInitAndCheckHooks(file:///data/data/org.nativescript.testkt/files/app/vendor.js:16872:9)
	at refreshView(file:///data/data/org.nativescript.testkt/files/app/vendor.js:23913:21)
	at renderComponentOrTemplate(file:///data/data/org.nativescript.testkt/files/app/vendor.js:24012:9)
	at tickRootContext(file:///data/data/org.nativescript.testkt/files/app/vendor.js:25243:9)
	at detectChangesInRootView(file:///data/data/org.nativescript.testkt/files/app/vendor.js:25268:5)
	at detectChanges(file:///data/data/org.nativescript.testkt/files/app/vendor.js:37288:9)
	at activateOnGoForward(file:///data/data/org.nativescript.testkt/files/app/vendor.js:70553:42)
	at activateWith(file:///data/data/org.nativescript.testkt/files/app/vendor.js:70524:14)
	at activateRoutes(file:///data/data/org.nativescript.testkt/files/app/vendor.js:60236:40)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:60187:18)
	at activateChildRoutes(file:///data/data/org.nativescript.testkt/files/app/vendor.js:60186:29)
	at activate(file:///data/data/org.nativescript.testkt/files/app/vendor.js:60107:14)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:60092:10)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:136370:37)
	at OperatorSubscriber._this._next(file:///data/data/org.nativescript.testkt/files/app/vendor.js:134765:21)
	at exports.modules../node_modules/rxjs/dist/cjs/internal/Subscriber.js.Subscriber.next(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132943:18)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:138115:28)
	at OperatorSubscriber._this._next(file:///data/data/org.nativescript.testkt/files/app/vendor.js:134765:21)
	at exports.modules../node_modules/rxjs/dist/cjs/internal/Subscriber.js.Subscriber.next(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132943:18)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:136370:24)
	at OperatorSubscriber._this._next(file:///data/data/org.nativescript.testkt/files/app/vendor.js:134765:21)
	at exports.modules../node_modules/rxjs/dist/cjs/internal/Subscriber.js.Subscriber.next(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132943:18)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:137903:195)
	at OperatorSubscriber._this._next(file:///data/data/org.nativescript.testkt/files/app/vendor.js:134765:21)
	at exports.modules../node_modules/rxjs/dist/cjs/internal/Subscriber.js.Subscriber.next(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132943:18)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:136370:24)
	at OperatorSubscriber._this._next(file:///data/data/org.nativescript.testkt/files/app/vendor.js:134765:21)
	at exports.modules../node_modules/rxjs/dist/cjs/internal/Subscriber.js.Subscriber.next(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132943:18)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:134216:24)
	at Observable._trySubscribe(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132505:25)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:132499:31)
	at errorContext(file:///data/data/org.nativescript.testkt/files/app/vendor.js:140501:9)
	at Observable.subscribe(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132490:41)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:136369:16)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:140807:28)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:132494:30)
	at errorContext(file:///data/data/org.nativescript.testkt/files/app/vendor.js:140501:9)
	at Observable.subscribe(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132490:41)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:137903:68)
	at OperatorSubscriber._this._next(file:///data/data/org.nativescript.testkt/files/app/vendor.js:134765:21)
	at exports.modules../node_modules/rxjs/dist/cjs/internal/Subscriber.js.Subscriber.next(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132943:18)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:137903:195)
	at OperatorSubscriber._this._next(file:///data/data/org.nativescript.testkt/files/app/vendor.js:134765:21)
	at exports.modules../node_modules/rxjs/dist/cjs/internal/Subscriber.js.Subscriber.next(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132943:18)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:136370:24)
	at OperatorSubscriber._this._next(file:///data/data/org.nativescript.testkt/files/app/vendor.js:134765:21)
	at exports.modules../node_modules/rxjs/dist/cjs/internal/Subscriber.js.Subscriber.next(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132943:18)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:138115:28)
	at OperatorSubscriber._this._next(file:///data/data/org.nativescript.testkt/files/app/vendor.js:134765:21)
	at exports.modules../node_modules/rxjs/dist/cjs/internal/Subscriber.js.Subscriber.next(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132943:18)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:137903:195)
	at OperatorSubscriber._this._next(file:///data/data/org.nativescript.testkt/files/app/vendor.js:134765:21)
	at exports.modules../node_modules/rxjs/dist/cjs/internal/Subscriber.js.Subscriber.next(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132943:18)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:138115:28)
	at OperatorSubscriber._this._next(file:///data/data/org.nativescript.testkt/files/app/vendor.js:134765:21)
	at exports.modules../node_modules/rxjs/dist/cjs/internal/Subscriber.js.Subscriber.next(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132943:18)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:136543:28)
	at OperatorSubscriber._this._next(file:///data/data/org.nativescript.testkt/files/app/vendor.js:134765:21)
	at exports.modules../node_modules/rxjs/dist/cjs/internal/Subscriber.js.Subscriber.next(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132943:18)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:136543:28)
	at OperatorSubscriber._this._next(file:///data/data/org.nativescript.testkt/files/app/vendor.js:134765:21)
	at exports.modules../node_modules/rxjs/dist/cjs/internal/Subscriber.js.Subscriber.next(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132943:18)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:134216:24)
	at Observable._trySubscribe(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132505:25)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:132499:31)
	at errorContext(file:///data/data/org.nativescript.testkt/files/app/vendor.js:140501:9)
	at Observable.subscribe(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132490:41)
	at doInnerSub(file:///data/data/org.nativescript.testkt/files/app/vendor.js:136537:61)
	at outerNext(file:///data/data/org.nativescript.testkt/files/app/vendor.js:136532:70)
	at OperatorSubscriber._this._next(file:///data/data/org.nativescript.testkt/files/app/vendor.js:134765:21)
	at exports.modules../node_modules/rxjs/dist/cjs/internal/Subscriber.js.Subscriber.next(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132943:18)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:138023:36)
	at OperatorSubscriber._this._complete(file:///data/data/org.nativescript.testkt/files/app/vendor.js:134788:21)
	at exports.modules../node_modules/rxjs/dist/cjs/internal/Subscriber.js.Subscriber.complete(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132961:18)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:138120:28)
	at OperatorSubscriber._this._complete(file:///data/data/org.nativescript.testkt/files/app/vendor.js:134788:21)
	at exports.modules../node_modules/rxjs/dist/cjs/internal/Subscriber.js.Subscriber.complete(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132961:18)
	at checkComplete(file:///data/data/org.nativescript.testkt/files/app/vendor.js:136529:24)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:136573:9)
	at OperatorSubscriber._this._complete(file:///data/data/org.nativescript.testkt/files/app/vendor.js:134788:21)
	at exports.modules../node_modules/rxjs/dist/cjs/internal/Subscriber.js.Subscriber.complete(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132961:18)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:134218:20)
	at Observable._trySubscribe(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132505:25)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:132499:31)
	at errorContext(file:///data/data/org.nativescript.testkt/files/app/vendor.js:140501:9)
	at Observable.subscribe(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132490:41)
	at mergeInternals(file:///data/data/org.nativescript.testkt/files/app/vendor.js:136571:12)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:136604:107)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:140807:28)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:132494:30)
	at errorContext(file:///data/data/org.nativescript.testkt/files/app/vendor.js:140501:9)
	at Observable.subscribe(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132490:41)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:138112:20)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:140807:28)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:132494:30)
	at errorContext(file:///data/data/org.nativescript.testkt/files/app/vendor.js:140501:9)
	at Observable.subscribe(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132490:41)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:138015:20)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:140807:28)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:132494:30)
	at errorContext(file:///data/data/org.nativescript.testkt/files/app/vendor.js:140501:9)
	at Observable.subscribe(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132490:41)
	at mergeInternals(file:///data/data/org.nativescript.testkt/files/app/vendor.js:136571:12)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:136604:107)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:140807:28)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:132494:30)
	at errorContext(file:///data/data/org.nativescript.testkt/files/app/vendor.js:140501:9)
	at Observable.subscribe(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132490:41)
	at doInnerSub(file:///data/data/org.nativescript.testkt/files/app/vendor.js:136537:61)
	at outerNext(file:///data/data/org.nativescript.testkt/files/app/vendor.js:136532:70)
	at OperatorSubscriber._this._next(file:///data/data/org.nativescript.testkt/files/app/vendor.js:134765:21)
	at exports.modules../node_modules/rxjs/dist/cjs/internal/Subscriber.js.Subscriber.next(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132943:18)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:134216:24)
	at Observable._trySubscribe(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132505:25)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:132499:31)
	at errorContext(file:///data/data/org.nativescript.testkt/files/app/vendor.js:140501:9)
	at Observable.subscribe(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132490:41)
	at mergeInternals(file:///data/data/org.nativescript.testkt/files/app/vendor.js:136571:12)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:136604:107)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:140807:28)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:132494:30)
	at errorContext(file:///data/data/org.nativescript.testkt/files/app/vendor.js:140501:9)
	at Observable.subscribe(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132490:41)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:138112:20)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:140807:28)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:132494:30)
	at errorContext(file:///data/data/org.nativescript.testkt/files/app/vendor.js:140501:9)
	at Observable.subscribe(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132490:41)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:137903:68)
	at OperatorSubscriber._this._next(file:///data/data/org.nativescript.testkt/files/app/vendor.js:134765:21)
	at exports.modules../node_modules/rxjs/dist/cjs/internal/Subscriber.js.Subscriber.next(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132943:18)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:138115:28)
	at OperatorSubscriber._this._next(file:///data/data/org.nativescript.testkt/files/app/vendor.js:134765:21)
	at exports.modules../node_modules/rxjs/dist/cjs/internal/Subscriber.js.Subscriber.next(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132943:18)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:134216:24)
	at Observable._trySubscribe(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132505:25)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:132499:31)
	at errorContext(file:///data/data/org.nativescript.testkt/files/app/vendor.js:140501:9)
	at Observable.subscribe(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132490:41)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:138112:20)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:140807:28)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:132494:30)
	at errorContext(file:///data/data/org.nativescript.testkt/files/app/vendor.js:140501:9)
	at Observable.subscribe(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132490:41)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:137899:16)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:140807:28)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:132494:30)
	at errorContext(file:///data/data/org.nativescript.testkt/files/app/vendor.js:140501:9)
	at Observable.subscribe(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132490:41)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:138112:20)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:140807:28)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:132494:30)
	at errorContext(file:///data/data/org.nativescript.testkt/files/app/vendor.js:140501:9)
	at Observable.subscribe(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132490:41)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:136369:16)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:140807:28)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:132494:30)
	at errorContext(file:///data/data/org.nativescript.testkt/files/app/vendor.js:140501:9)
	at Observable.subscribe(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132490:41)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:137903:68)
	at OperatorSubscriber._this._next(file:///data/data/org.nativescript.testkt/files/app/vendor.js:134765:21)
	at exports.modules../node_modules/rxjs/dist/cjs/internal/Subscriber.js.Subscriber.next(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132943:18)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:136049:162)
	at OperatorSubscriber._this._next(file:///data/data/org.nativescript.testkt/files/app/vendor.js:134765:21)
	at exports.modules../node_modules/rxjs/dist/cjs/internal/Subscriber.js.Subscriber.next(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132943:18)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:138115:28)
	at OperatorSubscriber._this._next(file:///data/data/org.nativescript.testkt/files/app/vendor.js:134765:21)
	at exports.modules../node_modules/rxjs/dist/cjs/internal/Subscriber.js.Subscriber.next(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132943:18)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:136543:28)
	at OperatorSubscriber._this._next(file:///data/data/org.nativescript.testkt/files/app/vendor.js:134765:21)
	at exports.modules../node_modules/rxjs/dist/cjs/internal/Subscriber.js.Subscriber.next(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132943:18)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:136370:24)
	at OperatorSubscriber._this._next(file:///data/data/org.nativescript.testkt/files/app/vendor.js:134765:21)
	at exports.modules../node_modules/rxjs/dist/cjs/internal/Subscriber.js.Subscriber.next(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132943:18)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:136543:28)
	at OperatorSubscriber._this._next(file:///data/data/org.nativescript.testkt/files/app/vendor.js:134765:21)
	at exports.modules../node_modules/rxjs/dist/cjs/internal/Subscriber.js.Subscriber.next(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132943:18)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:135677:28)
	at OperatorSubscriber._this._complete(file:///data/data/org.nativescript.testkt/files/app/vendor.js:134788:21)
	at exports.modules../node_modules/rxjs/dist/cjs/internal/Subscriber.js.Subscriber.complete(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132961:18)
	at exports.modules../node_modules/rxjs/dist/cjs/internal/Subscriber.js.Subscriber._complete(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132984:30)
	at exports.modules../node_modules/rxjs/dist/cjs/internal/Subscriber.js.Subscriber.complete(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132961:18)
	at exports.modules../node_modules/rxjs/dist/cjs/internal/Subscriber.js.Subscriber._complete(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132984:30)
	at exports.modules../node_modules/rxjs/dist/cjs/internal/Subscriber.js.Subscriber.complete(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132961:18)
	at checkComplete(file:///data/data/org.nativescript.testkt/files/app/vendor.js:136529:24)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:136573:9)
	at OperatorSubscriber._this._complete(file:///data/data/org.nativescript.testkt/files/app/vendor.js:134788:21)
	at exports.modules../node_modules/rxjs/dist/cjs/internal/Subscriber.js.Subscriber.complete(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132961:18)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:134218:20)
	at Observable._trySubscribe(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132505:25)
	at (file:///data/data/org.nativescript.testkt/files/app/vendor.js:132499:31)
	at errorContext(file:///data/data/org.nativescript.testkt/files/app/vendor.js:140501:9)
	at Observable.subscribe(file:///data/data/org.nativescript.testkt/files/app/vendor.js:132490:41)
	at mergeInternals(file:///data/data/org.nativescript.testkt/files/app/vendor.js:136571:12)
```
</details>
I set up a new android project to try this out using CLI version 8.1.4. Below is my package.json:

<details>

```
{
  "name": "testkt",
  "main": "./src/main.ts",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "@angular/animations": "^12.2.0",
    "@angular/common": "^12.2.0",
    "@angular/compiler": "^12.2.0",
    "@angular/core": "^12.2.0",
    "@angular/forms": "^12.2.0",
    "@angular/platform-browser": "^12.2.0",
    "@angular/platform-browser-dynamic": "^12.2.0",
    "@angular/router": "^12.2.0",
    "@nativescript/angular": "^12.2.0",
    "@nativescript/core": "~8.1.1",
    "@nativescript/google-signin": "^1.0.0-alpha.8",
    "@nativescript/theme": "~3.0.1",
    "rxjs": "~7.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^12.2.0",
    "@nativescript/android": "8.1.1",
    "@nativescript/types": "~8.1.1",
    "@nativescript/webpack": "~5.0.0",
    "@ngtools/webpack": "^12.2.0",
    "typescript": "~4.3.5"
  }
}
```
</details>

A similar problem was reported [here](https://github.com/CameraKit/blurkit-android/issues/43) so I suspect the solution is similarly simple.

Thanks!

**Comment by IndiTheo** [comment]
According to https://github.com/CameraKit/blurkit-android/issues/43, looks like you have to manually declare `kotlin-stdlib` as a dependency?
