### ISSUE TITLE
[background-http] Android: Crashes if targeting S+ version 32 +

### ISSUE THREAD

**Issue by LaKing** [NativeScript/plugins#217]
I had a working app, after updating everything to the latest version, my App crashes on android after starting `session.multipartUpload`.

```
System.err: java.lang.reflect.InvocationTargetException
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.tns.NativeScriptUncaughtExceptionHandler.uncaughtException(NativeScriptUncaughtExceptionHandler.java:58)
System.err: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
System.err: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
System.err: 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2200)
System.err: Caused by: java.lang.IllegalArgumentException: org.nativescript.Hangmaffia: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
System.err: Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
System.err: 	at android.app.PendingIntent.checkFlags(PendingIntent.java:382)
System.err: 	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:465)
System.err: 	at android.app.PendingIntent.getActivity(PendingIntent.java:451)
System.err: 	at android.app.PendingIntent.getActivity(PendingIntent.java:415)
System.err: 	at com.tns.ErrorReport.startPendingErrorActivity(ErrorReport.java:157)
System.err: 	at com.tns.ErrorReport.startActivity(ErrorReport.java:136)

```
Nativescript Vue

**Comment by LaKing** [comment]
triniwiz via Discord channel:
setting it to version 30 will work for now but the plugin and runtime will need to be updated

[A good guide for setting Android version 30](https://newbiescripter.com/how-to-set-target-api-level-for-android-project/)
