### ISSUE TITLE
[@nativescript/geolocation] Android 11 - One-time location permission revoked when app is moved to the background

### ISSUE THREAD

**Issue by tommag21** [NativeScript/plugins#279]
On Android 11 and above, when the location permission is requested the user can allow the app to access the device location "Only this time". When this option is selected and the app is moved to the background, after a short time (around one minute) the one time session expires and the app is killed. This behavior also occurs when an in-app browser is launched from the main NativeScript activity, which is how I found this issue.

I tested on an Android 11 emulator. The manifest includes ACCESS_COARSE_LOCATION, ACCESS_FINE_LOCATION, ACCESS_BACKGROUND_LOCATION permissions.
These are the device logs:
```
05-30 17:52:29.386 524 524 I OneTimePermissionUserManager: One time session expired for org.nativescript.temp (10163).
05-30 17:52:29.428 4559 4580 V PermissionControllerServiceImpl: Permission grant result requestId=-2574434414935562278 callingUid=10163 callingPackage=org.nativescript.temp permission=android.permission.ACCESS_FINE_LOCATION isImplicit=false result=15
05-30 17:52:29.428 4559 4580 V PermissionControllerServiceImpl: Permission grant result requestId=-2574434414935562278 callingUid=10163 callingPackage=org.nativescript.temp permission=android.permission.ACCESS_COARSE_LOCATION isImplicit=false result=15
05-30 17:52:29.473 524 3731 W AppOps : setUidMode() called with a mode inconsistent with runtime permission state, this is discouraged and you should revoke the runtime permission instead: uid=10163, switchCode=0, mode=1, permission=android.permission.ACCESS_COARSE_LOCATION
05-30 17:52:29.473 524 574 I ActivityManager: Killing 9104:org.nativescript.temp/u0a163 (adj 700): one-time permission revoked
05-30 17:52:29.583 524 4992 I WindowManager: WIN DEATH: Window{49ce565 u0 org.nativescript.temp/com.tns.NativeScriptActivity}
05-30 17:52:29.583 524 4992 W InputDispatcher: Attempted to unregister already unregistered input channel '49ce565 org.nativescript.temp/com.tns.NativeScriptActivity (server)'
05-30 17:52:29.588 289 289 I Zygote : Process 9104 exited due to signal 9 (Killed)
05-30 17:52:29.590 524 550 W ActivityManager: setHasOverlayUi called on unknown pid: 9104
05-30 17:52:29.616 524 558 I libprocessgroup: Successfully killed process cgroup uid 10163 pid 9104 in 138ms
05-30 17:52:32.302 209 212 E android.system.suspend@1.0-service: Error opening kernel wakelock stats for: wakeup34: Permission denied
05-30 17:52:32.299 209 209 W Binder:209_2: type=1400 audit(0.0:80): avc: denied { read } for name="wakeup34" dev="sysfs" ino=19014 scontext=u:r:system_suspend:s0 tcontext=u:object_r:sysfs:s0 tclass=dir permissive=0
05-30 17:52:32.320 209 212 E android.system.suspend@1.0-service: Error opening kernel wakelock stats for: wakeup35: Permission denied
05-30 17:52:32.315 209 209 W Binder:209_2: type=1400 audit(0.0:81): avc: denied { read } for name="wakeup35" dev="sysfs" ino=19077 scontext=u:r:system_suspend:s0 tcontext=u:object_r:sysfs:s0 tclass=dir permissive=0
```

To reproduce:
1. Create a new NS8 project (I was unable to run the demo app)
2. Install and configure the plugin
3. Call `enableLocationRequest`
4. Select "Only this time"
5. Minimize the app

Is it a default Android behavior or is it possibile to fix this issue, for example extending the one-time session duration?

**Comment by ebiscardi** [comment]
I occurred a similar problem with NS8 on Android 11. App crashes with this error:

```
An uncaught Exception occurred on "main" thread.
ClassNotFoundException when unmarshalling: androidx.core.widget.NestedScrollView$SavedState

StackTrace:
android.os.BadParcelableException: ClassNotFoundException when unmarshalling: androidx.core.widget.NestedScrollView$SavedState
	at android.os.Parcel.readParcelableCreator(Parcel.java:3364)
	at android.os.Parcel.readParcelable(Parcel.java:3272)
	at android.view.AbsSavedState.<init>(AbsSavedState.java:67)
	at android.view.View$BaseSavedState.<init>(View.java:28684)
	at android.view.View$BaseSavedState.<init>(View.java:28673)
	at org.nativescript.widgets.HorizontalScrollView$SavedState.<init>(HorizontalScrollView.java:283)
	at org.nativescript.widgets.HorizontalScrollView$SavedState$1.createFromParcel(HorizontalScrollView.java:307)
	at org.nativescript.widgets.HorizontalScrollView$SavedState$1.createFromParcel(HorizontalScrollView.java:305)
	at android.os.Parcel.readParcelable(Parcel.java:3281)
	at android.os.Parcel.readValue(Parcel.java:3174)
	at android.os.Parcel.readSparseArrayInternal(Parcel.java:3650)
	at android.os.Parcel.readSparseArray(Parcel.java:2792)
	at android.os.Parcel.readValue(Parcel.java:3231)
	at android.os.Parcel.readArrayMapInternal(Parcel.java:3567)
	at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
	at android.os.BaseBundle.unparcel(BaseBundle.java:236)
	at android.os.Bundle.getSparseParcelableArray(Bundle.java:1079)
	at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2179)
	at android.app.Activity.onRestoreInstanceState(Activity.java:1679)
	at android.app.Activity.performRestoreInstanceState(Activity.java:1632)
	at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1356)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3491)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

The crash occurs if the user allows to access the position only one time, resuming after some time the app from background

You can reproduce the issue more easily in this way:
- open the app and give permission 'while using the app'
- put the app in background
- change the app permission to 'only one time' from android settings
- resume the app

@tommag21 did you find a solution to this?

**Comment by SamerAtawna** [comment]
Hi I have the same issue, currently on android 12 sdk 31 

> Class not found when unmarshalling: androidx.core.widget.NestedScrollView$SavedState
                                                                                                    java.lang.ClassNotFoundException: androidx.core.widget.NestedScrollView$SavedState
                                                                                                    	at java.lang.Class.classForName(Native Method)
                                                                                                    	at java.lang.Class.forName(Class.java:454)
                                                                                                    	at android.os.Parcel.readParcelableCreator(Parcel.java:3390)
                                                                                                    	at android.os.Parcel.readParcelable(Parcel.java:3324)
                                                                                                    	at android.view.AbsSavedState.<init>(AbsSavedState.java:67)
                                                                                                    	at android.view.View$BaseSavedState.<init>(View.java:29055)
                                                                                                    	at android.view.View$BaseSavedState.<init>(View.java:29044)
                                                                                                    	at org.nativescript.widgets.HorizontalScrollView$SavedState.<init>(HorizontalScrollView.java:283)
                                                                                                    	at org.nativescript.widgets.HorizontalScrollView$SavedState$1.createFromParcel(HorizontalScrollView.java:307)
                                                                                                    	at org.nativescript.widgets.HorizontalScrollView$SavedState$1.createFromParcel(HorizontalScrollView.java:305)
                                                                                                    	at android.os.Parcel.readParcelable(Parcel.java:3333)
                                                                                                    	at android.os.Parcel.readValue(Parcel.java:3226)
                                                                                                    	at android.os.Parcel.readSparseArrayInternal(Parcel.java:3706)
                                                                                                    	at android.os.Parcel.readSparseArray(Parcel.java:2844)
                                                                                                    	at android.os.Parcel.readValue(Parcel.java:3283)
                                                                                                    	at android.os.Parcel.readArrayMapInternal(Parcel.java:3623)
                                                                                                    	at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
                                                                                                    	at android.os.BaseBundle.unparcel(BaseBundle.java:236)
                                                                                                    	at android.os.Bundle.getSparseParcelableArray(Bundle.java:1080)
                                                                                                    	at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2198)
                                                                                                    	at android.app.Activity.onRestoreInstanceState(Activity.java:1724)
                                                                                                    	at android.app.Activity.performRestoreInstanceState(Activity.java:1677)
                                                                                                    	at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1376)
                                                                                                    	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3676)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7839)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
                                                                                                    Caused by: java.lang.ClassNotFoundException: androidx.core.widget.NestedScrollView$SavedState
                                                                                                    	at java.lang.Class.classForName(Native Method)
                                                                                                    	at java.lang.BootClassLoader.findClass(ClassLoader.java:1358)
                                                                                                    	at java.lang.BootClassLoader.loadClass(ClassLoader.java:1418)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at java.lang.Class.classForName(Native Method) 
                                                                                                    	at java.lang.Class.forName(Class.java:454) 
                                                                                                    	at android.os.Parcel.readParcelableCreator(Parcel.java:3390) 
                                                                                                    	at android.os.Parcel.readParcelable(Parcel.java:3324) 
                                                                                                    	at android.view.AbsSavedState.<init>(AbsSavedState.java:67) 
                                                                                                    	at android.view.View$BaseSavedState.<init>(View.java:29055) 
                                                                                                    	at android.view.View$BaseSavedState.<init>(View.java:29044) 
                                                                                                    	at org.nativescript.widgets.HorizontalScrollView$SavedState.<init>(HorizontalScrollView.java:283) 
                                                                                                    	at org.nativescript.widgets.HorizontalScrollView$SavedState$1.createFromParcel(HorizontalScrollView.java:307) 
                                                                                                    	at org.nativescript.widgets.HorizontalScrollView$SavedState$1.createFromParcel(HorizontalScrollView.java:305) 
                                                                                                    	at android.os.Parcel.readParcelable(Parcel.java:3333) 
                                                                                                    	at android.os.Parcel.readValue(Parcel.java:3226) 
                                                                                                    	at android.os.Parcel.readSparseArrayInternal(Parcel.java:3706) 
                                                                                                    	at android.os.Parcel.readSparseArray(Parcel.java:2844) 
                                                                                                    	at android.os.Parcel.readValue(Parcel.java:3283) 
                                                                                                    	at android.os.Parcel.readArrayMapInternal(Parcel.java:3623) 
                                                                                                    	at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292) 
                                                                                                    	at android.os.BaseBundle.unparcel(BaseBundle.java:236) 
                                                                                                    	at android.os.Bundle.getSparseParcelableArray(Bundle.java:1080) 
                                                                                                    	at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2198) 
                                                                                                    	at android.app.Activity.onRestoreInstanceState(Activity.java:1724) 
                                                                                                    	at android.app.Activity.performRestoreInstanceState(Activity.java:1677) 
                                                                                                    	at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1376) 
                                                                                                    	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3676) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7839) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

anyone have any progress on this? thanks
