### ISSUE TITLE
[@nativescript/social-share] Crash on Android when navigating back

### ISSUE THREAD

**Issue by manijak** [NativeScript/plugins#287]
We are using this plugin to in our sub-view (news article) so users can share content. Sharing functions works fine, but when navigating from the sub-view back to main-view, the app crashes. 

MainView > Article > Share (Message/Bluetooth/Gmail ect) > Navigate back to main = crash

Code for back-navigation:
```javascript
export function tapBack(args: EventData){
    Frame.topmost().goBack();
}
```

```console
System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method onCreateView failed
System.err: Error: java.lang.IllegalStateException: Expected the adapter to be 'fresh' while restoring state.
System.err:
System.err: StackTrace:
System.err: onCreateView(file: node_modules/@nativescript/core/ui/frame/index.android.js:757:0)
System.err: 	at onCreateView(file: node_modules/@nativescript/core/ui/frame/fragment.android.js:28:0)
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1302)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1188)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1175)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1153)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1149)
System.err: 	at com.tns.FragmentClass.onCreateView(FragmentClass.java:55)
System.err: 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2995)
System.err: 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:523)
System.err: 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
System.err: 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
System.err: 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1758)
System.err: 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
System.err: 	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:488)
System.err: 	at android.os.Handler.handleCallback(Handler.java:938)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
System.err: 	at android.os.Looper.loopOnce(Looper.java:201)
System.err: 	at android.os.Looper.loop(Looper.java:288)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7842)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
System.err: Caused by: java.lang.IllegalStateException: Expected the adapter to be 'fresh' while restoring state.
System.err: 	at androidx.viewpager2.adapter.FragmentStateAdapter.restoreState(FragmentStateAdapter.java:536)
System.err: 	at androidx.viewpager2.widget.ViewPager2.restorePendingState(ViewPager2.java:350)
System.err: 	at androidx.viewpager2.widget.ViewPager2.dispatchRestoreInstanceState(ViewPager2.java:375)
System.err: 	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4006)
System.err: 	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4006)
System.err: 	at android.view.View.restoreHierarchyState(View.java:21055)
System.err: 	... 22 more
JS: [app.js]: Uncaught NativeScript Error: Error: Calling js method onCreateView failed
JS: Error: java.lang.IllegalStateException: Expected the adapter to be 'fresh' while restoring state.
```

```yaml
OS: macOS 12.2
CPU: (8) arm64 Apple M1 Pro
Shell: /bin/zsh
node: 16.15.0
npm: 8.5.5
nativescript: 8.2.3

# android
java: 11.0.15
ndk: Not Found
apis: 30, 31, 32
build_tools: 30.0.3, 32.0.0, 32.1.0
system_images:
  - android-32 | Google APIs ARM 64 v8a
  - android-32 | Google Play ARM 64 v8a

# ios
xcode: 13.4.1/13F100
cocoapods: 1.11.3
python: 2.7.18
python3: 3.8.9
ruby: 2.6.8
platforms:
  - DriverKit 21.4
  - iOS 15.5
  - macOS 12.3
  - tvOS 15.4
  - watchOS 8.5
```

### Dependencies

```json
"dependencies": {
  "@nativescript-community/ui-material-bottom-navigation": "^7.0.18",
  "@nativescript-community/ui-material-cardview": "^7.0.18",
  "@nativescript-community/ui-pulltorefresh": "^2.5.1",
  "@nativescript/core": "~8.2.4",
  "@nativescript/firebase-analytics": "^2.1.0",
  "@nativescript/firebase-core": "^2.1.0",
  "@nativescript/firebase-messaging": "^2.1.0",
  "@nativescript/iqkeyboardmanager": "^2.0.0",
  "@nativescript/local-notifications": "^6.0.0",
  "@nativescript/secure-storage": "^3.0.0",
  "@nativescript/social-share": "^2.0.4",
  "@nativescript/theme": "^3.0.2",
  "@nstudio/nativescript-cardview": "^2.0.1",
  "@nstudio/nativescript-carousel": "^8.0.3",
  "@triniwiz/nativescript-image-cache-it": "^7.0.14",
  "@triniwiz/nativescript-image-zoom": "^4.1.2",
  "@triniwiz/nativescript-youtubeplayer": "^4.1.4",
  "code-128-encoder": "^3.1.1",
  "moment": "^2.29.3",
  "nativescript-appversion": "https://github.com/EddyVerbruggen/nativescript-appversion",
  "nativescript-clipboard": "^2.1.1",
  "nativescript-feedback": "^2.0.0",
  "nativescript-qr-generator": "^3.0.0",
  "nativescript-ui-listview": "^10.1.1"
},
"devDependencies": {
  "@nativescript/android": "8.2.3",
  "@nativescript/ios": "8.2.3",
  "@nativescript/types": "~8.2.0",
  "@nativescript/webpack": "5.0.6",
  "@typescript-eslint/parser": "^5.22.0",
  "eslint": "8.14.0",
  "eslint-plugin-nativescript": "0.0.0",
  "sass": "1.51.0",
  "sass-loader": "12.6.0",
  "typescript": "4.5.5"
}
```

**Comment by manijak** [comment]
Related to https://github.com/NativeScript/NativeScript/issues/9856
