### ISSUE TITLE
[background-http] App crashes due to IllegalArgumentException

### ISSUE THREAD

**Issue by grigala** [NativeScript/plugins#318]
Latest `@nativescript/background-http` crashes some Android devices with `You have to set namespace to your app package name (context.packageName) in your Application subclass`:

```
Caused by: java.lang.IllegalArgumentException:
  at net.gotev.uploadservice.UploadServiceConfig.getNamespace (UploadServiceConfig.kt:74)
  at net.gotev.uploadservice.UploadServiceConfig.getBroadcastNotificationAction (UploadServiceConfig.kt:234)
  at net.gotev.uploadservice.UploadServiceConfig.getBroadcastNotificationActionIntentFilter (UploadServiceConfig.kt:248)
  at net.gotev.uploadservice.observer.request.NotificationActionsObserver.register (NotificationActionsObserver.kt:31)
  at net.gotev.uploadservice.UploadService.onCreate (UploadService.kt:194)
  at android.app.ActivityThread.handleCreateService (ActivityThread.java:4641)
```

Full trace from Google Play Console:
```
java.lang.RuntimeException: 
  at android.app.ActivityThread.handleCreateService (ActivityThread.java:4655)
  at android.app.ActivityThread.access$2800 (ActivityThread.java:251)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2319)
  at android.os.Handler.dispatchMessage (Handler.java:110)
  at android.os.Looper.loop (Looper.java:219)
  at android.app.ActivityThread.main (ActivityThread.java:8393)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:513)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1055)
Caused by: java.lang.IllegalArgumentException: 
  at net.gotev.uploadservice.UploadServiceConfig.getNamespace (UploadServiceConfig.kt:74)
  at net.gotev.uploadservice.UploadServiceConfig.getBroadcastNotificationAction (UploadServiceConfig.kt:234)
  at net.gotev.uploadservice.UploadServiceConfig.getBroadcastNotificationActionIntentFilter (UploadServiceConfig.kt:248)
  at net.gotev.uploadservice.observer.request.NotificationActionsObserver.register (NotificationActionsObserver.kt:31)
  at net.gotev.uploadservice.UploadService.onCreate (UploadService.kt:194)
  at android.app.ActivityThread.handleCreateService (ActivityThread.java:4641)
```

Calling `init()` from the `main.ts` does not help this particular problem, because error occurs while having this in my `main.ts`:
```typescript
import { init } from "@nativescript/background-http";

init();
``` 

According to https://github.com/gotev/android-upload-service/issues/510 `createNotificationChannel()` needs to be called explicitly.

**Comment by madmas** [comment]
Might be related to #274

**Comment by pap5508** [comment]
@grigala : Have you found a solution for this? I am also stuck with the same problem

**Comment by grigala** [comment]
Hi @pap5508, nothing that's 100% tested so far, but you can give it a try and do this before you call/construct bghttp session:

```typescript
 if (android.os.Build.VERSION.SDK_INT >= 26) {
            const channel = new android.app.NotificationChannel(
                "NotificationChannel", 
                "My App", 
                android.app.NotificationManager.IMPORTANCE_HIGH // adjust to your requirement
            );
            const manager = Utils.android
                .getApplicationContext()
                .getSystemService(android.content.Context.NOTIFICATION_SERVICE) as android.app.NotificationManager;

            manager.createNotificationChannel(channel);
        }
```

**Comment by LaKing** [comment]
> ```ts
> if (android.os.Build.VERSION.SDK_INT >= 26) { ...
> ```
I can't get it working with this. Get the same error.

**Comment by LaKing** [comment]
The `init()` function is new, .. after adding it I have this issue resolved for now.

**Comment by Maxeeezy** [comment]
I face the same issue. However, the init() calling before uploading multipart still gives me the same error... Where are you calling the init? main.ts still?

**Comment by pap5508** [comment]
@Maxeeezy : Yes, I have added in main.ts and working fine.

**Comment by chimmelb** [comment]
I run into this issue as well on Android. Not every upload (we use `init()`) but some fail. 

```
Caused by java.lang.IllegalArgumentException: You have to set namespace to your app package name (context.packageName) in your Application subclass
       at net.gotev.uploadservice.UploadServiceConfig.getNamespace(UploadServiceConfig.kt:74)
       at net.gotev.uploadservice.UploadServiceConfig.getBroadcastNotificationAction(UploadServiceConfig.kt:234)
       at net.gotev.uploadservice.UploadServiceConfig.getBroadcastNotificationActionIntentFilter(UploadServiceConfig.kt:248)
```

(extra info but theory: I think it's related to coming back from a Camera activity and somehow that namespace is not ready. I called init() in appResume (should be idempotent if already initialized) but that doesn't seem to fix it completely)

**Comment by EricAtGrasset** [comment]
import { Application } from '@nativescript/core';

Application.android.on('activityCreated', (args) => {
    if (args.activity) {
        const context = args.activity;
        const CHANNEL_ID = 'default_channel_id';
        const CHANNEL_NAME = 'Default Channel';

        const NotificationManagerCompat = androidx.core.app.NotificationManagerCompat;
        const NotificationChannel = android.app.NotificationChannel;
        const NotificationManager = android.app.NotificationManager;
        const Importance = android.app.NotificationManager.IMPORTANCE_HIGH;

        const channel = new NotificationChannel(CHANNEL_ID, CHANNEL_NAME, Importance);
        channel.setDescription('Default Notification Channel');
        const notificationManager = context.getSystemService(NotificationManager.class);
        notificationManager.createNotificationChannel(channel);
    }
});

**Comment by nielswitte** [comment]
> I run into this issue as well on Android. Not every upload (we use `init()`) but some fail.
> 
> ```
> Caused by java.lang.IllegalArgumentException: You have to set namespace to your app package name (context.packageName) in your Application subclass
>        at net.gotev.uploadservice.UploadServiceConfig.getNamespace(UploadServiceConfig.kt:74)
>        at net.gotev.uploadservice.UploadServiceConfig.getBroadcastNotificationAction(UploadServiceConfig.kt:234)
>        at net.gotev.uploadservice.UploadServiceConfig.getBroadcastNotificationActionIntentFilter(UploadServiceConfig.kt:248)
> ```
> 
> (extra info but theory: I think it's related to coming back from a Camera activity and somehow that namespace is not ready. I called init() in appResume (should be idempotent if already initialized) but that doesn't seem to fix it completely)

I am experiencing the same issue. Sometimes it throws the exception about a missing namespace when returning from the camera.
