### ISSUE TITLE
unable to build the package

### ISSUE THREAD

**Issue by luffyzc** [NativeScript/plugins#86]
I follow the guide:
1.  npm run setup
2. npm start, and then select build-all

I see this error 
```
? NativeScript Plugins ~ made with ❤️  Choose a command to start... @nativescript.build-all                               Build all packages
nps is executing `@nativescript.build-all` : nx run all:build
internal/modules/cjs/loader.js:625
  throw e;
  ^

Error: No valid exports main found for '/Users/chizhang/Program/plugin/ns/plugins/node_modules/@nrwl/cli/node_modules/yargs-parser'
    at resolveExportsTarget (internal/modules/cjs/loader.js:622:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:654:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/chizhang/Program/plugin/ns/plugins/node_modules/@nrwl/cli/lib/parse-run-one-options.js:4:21)
    at Module._compile (internal/modules/cjs/loader.js:1139:30) {
  code: 'MODULE_NOT_FOUND'
}
The script called "@nativescript.build-all" which runs "nx run all:build" failed with exit code 1 https://github.com/sezna/nps/blob/master/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
```

**Comment by rigor789** [comment]
@luffyzc what is your node version?

**Comment by luffyzc** [comment]
@rigor789 
Node version 10.21.0
ns version 7.0.12

**Comment by NathanWalker** [comment]
Can you use node 12 - 14?
Nativescript in general needs at least node 12. Just stay below 15 (12-14)

**Comment by luffyzc** [comment]
it works when I use 
node v14.15.4
ns 7.2.0 

Thanks
